# Configuração de Data Sources do Grafana
# Copie para /etc/grafana/provisioning/datasources/datasources.yml no servidor Grafana

apiVersion: 1

datasources:
  # Prometheus - Métricas
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.1.193:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  # Loki - Logs
  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.1.193:3100
    editable: true
    jsonData:
      maxLines: 1000
